### ISSUE TITLE
[Quest] Cold Hearted

### ISSUE THREAD

**Issue by Ben1o** [RaphaelSunwell/Sunwell-BugTracker#483]
**Opis**: W misji ratujemy zamrożonych więźniów i smoki za pomocą tych drugich, jednak nie mamy od samego początku pełnej kontroli nad smokiem

**Obecne działanie**: Po wskoczeniu z fly mounta na smoka nie mamy nad nim pełnej kontroli, możemy latać tylko w poziomie, dopiero gdy naciśniemy klawisz skoku dostajemy pełną kontrolę nad kierunkiem lotu smoka. Może to być kłopotliwe dla ludzi którzy będą pierwszy raz robić ową misję

**Oczekiwane działanie**: Po wejściu na smoka powinniśmy mieć nad nim pełną kontrolę

**Co należy zrobić, aby odtworzyć ten błąd**:
1. Uruchomić misję
2. Podlecieć do któregokolwiek ze smoków i wskoczyć na niego
3. Bez klikania na klawisz skoku (w przypadku mountów pionowego wznoszenia) próbować sterować smokiem

**Linki WoWHead/OpenWoW**:
1. Misja: http://www.wowhead.com/quest=12856/cold-hearted
2. Smoki: http://www.wowhead.com/npc=29708/captive-proto-drake
3. 

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
![wowscrnshot_103016_092838](https://cloud.githubusercontent.com/assets/22753220/19835370/b361653e-9e84-11e6-9b60-35ead4b0e50b.jpg)

**Comment by nexx94** [comment]
Problem ze sterowaniem mountami pojawia się również w innych questach z latającymi vehicle, ale wygląda że na globie również tak było. Komentarze (co prawda z późniejszych patchy:
"If you're having issues with moving vertically, try using the spacebar once, then "x" should work."
"Quest is acting up as of 12/1/2012. As soon as I jump on a protodrake from my flying mount, I can fly the protodrake around, but I am unable to go up and down using the mouse. I finally figured out that I had to use the spacebar to fly up for a moment in order to get the thing to fly properly."
"I do not think the quest is bugged. I thought so at first as well but I just hit the space bar to get my drake out of harms way and after doing that I was able to decend and get the prisoners. So, if you are unable to fly down on your drake just hit the space to fly up a little and that should fix it."
Uroki Wotlk moim zdaniem ale pewnie można by naprawić.
