### ISSUE TITLE
[Naxxramas] Grobbulus.

### ISSUE THREAD

**Issue by kovaq** [RaphaelSunwell/Sunwell-BugTracker#553]
[//]: # (****************************************************************)
[//]: # (** NIE USUWAJ TEGO SZABLONU, ALBO TWÓJ STYL ZOSTANIE USUNIĘTY **)
[//]: # (****************************************************************)

**Opis**: Chwile myslalem czy podpiac to jako grobbulusa, czy jako class spell rogala, ale ostatecznie jezeli bedzie cos zepsutego to wlasnie w tym debuffie od grobulka.
https://youtu.be/2qUOUyYm47E?t=47m32s
CoS ma 100% skutecznosc jezeli chodzi o zdjecie debuffa, a dopiero potem kazdy kolejny rzucony ma 10% ze wjedzie na mnie. (w przypadku lava burstow shamana ally to jest 100% i tak - taka mala anegdotka xd) Spell of Grobbulusa to natomiast disease, wiec jest jak najbardziej dispelable.

**Obecne działanie**: Disease od Grobbulusa nie zostal zdispelowany CoS'em.

**Oczekiwane działanie**: Disease of Grobbulusa powinien zostac zdispellowany przez CoS'a pozostawiajac po sobie plame w miejscu dispella.

**Co należy zrobić, aby odtworzyć ten błąd**:

1. Rozpoczac encounter z Grobbulusem
2. Poczekac, az rzuci na nas debuff.
3. Uzyc CoS'a na rogalu. (Cloak of Shadows)

**Linki WoWHead/OpenWoW**:

1. http://wotlk.openwow.com/spell=31224
2. http://www.wowhead.com/spell=28169/mutating-injection
3. http://www.wowhead.com/npc=15931/grobbulus#article

**Lokalizacja z koordynatów GPS (X, Y, Z, Map)**:
http://screenshooter.net/103008095/iljpddg (gps z naxxa, brak mozliwosci dojscia do bossa na nowym id)

**Comment by nexx94** [comment]
By Bladescope (1,487 – 6·21) on 2008/12/23 (Patch 3.0.3)		
The Rogue ability Cloak of Shadows does indeed remove the debuff (as described) without any consequence.
The reason why is because Cloak of Shadows "Removes" all harmful spell effects as opposed to Cleansing or Dispelling.

If a rogue was to receive this debuff, he could use Cloak of Shadows without having to move away. No one gets damaged and no poison cloud is placed.
5
Shoryukos on 2009/01/18 (Patch 3.0.3)
Cloak of shadows will NOT remove this debuff, or protect against the initial damage it causes. It is, however, useful to negate the aura damage the slimes will do.

Komentarz z większą ilością plusów to ten 2gi, który twierdzi że obecnie działa dobrze.
http://www.wowhead.com/forums&topic=77536/cloak-of-shadows-on-mutating-injection
Dodatkowo temat w którym ludzie opisują że na globie CoS nie dispellował debuffu.
https://foreveranoob.wordpress.com/2009/02/23/a-rogue-in-naxxramas-grobbulus/
Tu to samo.
Podsumowując, moim zdaniem obecne działanie jest poprawne.

**Comment by kovaq** [comment]
Jestem sklonny uznac, mimo to prosze o sprawdzenie, czy aby wszystko jest z tym okej, poki co niezamykam :)

**Comment by nexx94** [comment]
Zgaduje że to kwestia podejścia, ale ja uważam że bugi należy zgłaszać kiedy ma się przynajmniej 90% pewności że jest źle i ma się jakiś dowód żeby to potwierdzić. Co konkretnie administracja miałaby sprawdzać że jest OK? Jak dla mnie do zamknięcia do czasu aż pojawi się jakiś powód żeby otworzyć, w chwili obecnej to jest na zasadzie "no w zasadzie nie wiem czy coś w ogóle jest źle ale niech wisi otwarte"

**Comment by kovaq** [comment]
Zaden komentarz nie jest z oficjalnego zrodla. Sa to jedynie sugestie, pokazujace Twoja racje do co braku mozliwosci zdispelowania tego debuffa. Czemu mam zamknac temat, skoro nie ma dowodu 100% bledu w zgloszeniu?

**Comment by nexx94** [comment]
Z regulaminu Bugtrackera:
Zanim zgłosisz błąd
Upewnij się, że zgłaszana rzecz na pewno działa nieprawidłowo. W przypadku gry - nie zalecane jest sugerowanie się mechaniką, która jest dostępna na obecnym dodatku.

To ty masz udowodnić że jest źle, a nie administracja że jest dobrze.
